language: r
pandoc_version: 1.19.2.1
before_script:
- chmod +x ./website/_build.sh
- chmod +x ./website/_deploy.sh
script:
- "./website/_build.sh"
- "./website/_deploy.sh"
env:
  global:
    secure: p4G8F3P7PzES4BNVGWvWiMCnvPmkQjf9xPUmCzZFms7TBGDbPpol1CJw8m9jmgApXMVrZ88LAxnX0Dazwed5HTjVeFL2Fl4hxqplqvujK1F1gPHuO8OeQ8bX/hQKaZBQA1buYO3//mB7d3+qV7Cg66pM8QGkttHqehiq7I6DuQWtuqQTLwVXGdpqYGlH56Uh3RvMQEmqzp2GT3p0SoMAkh2FSkajeB3jmHvqjSgyjCCuq0QWKjQMpZMmQnHYye1YsPNg9Qh8oNcSinWoYdt/iQQ14A2hx3Hjkk0QOcWOYFhcYgmyj6fdF6sZ/ytClObroviFO7DjR4+JLqPW0WZFipPRKNY8ppJM5+QgJpO5a35lWJEjA8vX3qztnnUCkboHNx5rzRWYjH4UGq+7jYUANiQtSkGn2zTE+VxsqSdCEYe1uDdZbFrMOP7JwDiNSPm+fQq47KTrEQTkkKyqyMHOWeSwS19svguEZedJP/duW5TI7LwAEeYw9grCnKWGlQCx+193/ohlB/JX33LvArV5UMHNR9uaeIb7VpDpSdfL6uW+/7w9ByrRJ2x90qikM87kPcHzBg/qgYUsYltIMnLtLlHmzXbvOpuOgs6FDJy65M6JeU6yYrZEjS3tKys9+uNbe05I4h84IQO5k9ZgOLRHC5wkOiscWAjuYDEwXyCaQCU=
